name: app_version
description: Package for checking new app version.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  package_info_plus: ^4.0.2

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
